
CREATE TABLE braindump."Album" (
    "albumId" integer NOT NULL,
    "albumName" character varying(255),
    "authorUserId" integer
);

ALTER TABLE braindump."Album" ALTER COLUMN "albumId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME braindump."Album_album_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE braindump."Article" (
    "articleId" integer NOT NULL,
    title character varying(255),
    "articleBody" text,
    "authorUserId" integer,
    "privacyFlag" "char",
    "createdTimestamp" timestamp without time zone,
    "starCount" integer,
    "albumId" integer,
    "publishFlag" "char"
);


CREATE TABLE braindump."ArticleAlbum" (
    "albumId" integer NOT NULL,
    "articleId" integer NOT NULL,
    "createdTimestamp" timestamp without time zone
);




CREATE TABLE braindump."ArticleTag" (
    "tagId" integer NOT NULL,
    "articleId" integer NOT NULL
);


ALTER TABLE braindump."Article" ALTER COLUMN "articleId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME braindump."Article_article_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE braindump."Comment" (
    "commentId" integer NOT NULL,
    "commentBody" text,
    "createdTimestamp" timestamp without time zone,
    "articleId" integer NOT NULL,
    "replyToCommentId" integer,
    "commentUserId" integer NOT NULL
);

ALTER TABLE braindump."Comment" ALTER COLUMN "commentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME braindump."Comment_comment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE braindump."Engagement" (
    "articleId" integer NOT NULL,
    "viewCount" integer,
    "commentCount" integer
);


CREATE TABLE braindump."Subscription" (
    "createdTimestamp" timestamp without time zone,
    "subscriberUserId" integer NOT NULL,
    "authorUserId" integer NOT NULL,
    "subscriptionId" integer NOT NULL
);


ALTER TABLE braindump."Subscription" ALTER COLUMN "subscriptionId" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME braindump."Subscription_subscriptionId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE braindump."Tag" (
    "tagId" integer NOT NULL,
    "tagName" character varying(255) NOT NULL
);

ALTER TABLE braindump."Tag" ALTER COLUMN "tagId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME braindump."Tag_tag_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE braindump."User" (
    "userId" integer NOT NULL,
    "userName" character varying(255),
    "emailAddress" character varying(255),
    password character varying(255),
    "createdTimestamp" timestamp without time zone,
    "providerFlag" "char",
    "iconFilename" character varying(255),
    biography character varying(255)
);

ALTER TABLE braindump."User" ALTER COLUMN "userId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME braindump."User_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY braindump."ArticleAlbum"
    ADD CONSTRAINT "Album_Article_pkey" PRIMARY KEY ("albumId", "articleId");




ALTER TABLE ONLY braindump."Album"
    ADD CONSTRAINT "Album_pkey" PRIMARY KEY ("albumId");



ALTER TABLE ONLY braindump."ArticleTag"
    ADD CONSTRAINT "ArticleTag_pkey" PRIMARY KEY ("tagId", "articleId");



ALTER TABLE ONLY braindump."Article"
    ADD CONSTRAINT "Article_pkey" PRIMARY KEY ("articleId");



ALTER TABLE ONLY braindump."Comment"
    ADD CONSTRAINT "Comment_pkey" PRIMARY KEY ("commentId");




ALTER TABLE ONLY braindump."Engagement"
    ADD CONSTRAINT "Engagement_pkey" PRIMARY KEY ("articleId");




ALTER TABLE ONLY braindump."Tag"
    ADD CONSTRAINT "Tag_pkey" PRIMARY KEY ("tagId");




ALTER TABLE ONLY braindump."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY ("userId");




ALTER TABLE ONLY braindump."Subscription"
    ADD CONSTRAINT "subscriptionId_Pkey" PRIMARY KEY ("subscriptionId");

