
CREATE TABLE public."Album" (
    "albumId" integer NOT NULL,
    "albumName" character varying(255),
    "authorUserId" integer
);

ALTER TABLE public."Album" ALTER COLUMN "albumId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Album_album_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."Article" (
    "articleId" integer NOT NULL,
    title character varying(255),
    "articleBody" text,
    "authorUserId" integer,
    "privacyFlag" "char",
    "createdTimestamp" timestamp without time zone,
    "starCount" integer,
    "albumId" integer,
    "publishFlag" "char"
);


CREATE TABLE public."ArticleAlbum" (
    "albumId" integer NOT NULL,
    "articleId" integer NOT NULL,
    "createdTimestamp" timestamp without time zone
);




CREATE TABLE public."ArticleTag" (
    "tagId" integer NOT NULL,
    "articleId" integer NOT NULL
);


ALTER TABLE public."Article" ALTER COLUMN "articleId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Article_article_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public."Comment" (
    "commentId" smallint NOT NULL,
    "commentBody" character varying(255),
    "createdTimestamp" timestamp without time zone,
    "articleId" integer NOT NULL,
    "replyToCommentId" integer,
    "commentUserId" integer NOT NULL
);

ALTER TABLE public."Comment" ALTER COLUMN "commentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Comment_comment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."Engagement" (
    "articleId" integer NOT NULL,
    "viewCount" integer,
    "commentCount" integer
);


CREATE TABLE public."Subscription" (
    "createdTimestamp" timestamp without time zone,
    "subscriberUserId" integer NOT NULL,
    "authorUserId" integer NOT NULL,
    "subscriptionId" integer NOT NULL
);


ALTER TABLE public."Subscription" ALTER COLUMN "subscriptionId" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Subscription_subscriptionId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public."Tag" (
    "tagId" integer NOT NULL,
    "tagName" character varying(255) NOT NULL
);

ALTER TABLE public."Tag" ALTER COLUMN "tagId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tag_tag_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."User" (
    "userId" integer NOT NULL,
    "userName" character varying(255),
    "emailAddress" character varying(255),
    password character varying(255),
    "createdTimestamp" timestamp without time zone,
    "providerFlag" "char",
    "iconFilename" character varying(255),
    biography character varying(255)
);

ALTER TABLE public."User" ALTER COLUMN "userId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public."ArticleAlbum"
    ADD CONSTRAINT "Album_Article_pkey" PRIMARY KEY ("albumId", "articleId");




ALTER TABLE ONLY public."Album"
    ADD CONSTRAINT "Album_pkey" PRIMARY KEY ("albumId");



ALTER TABLE ONLY public."ArticleTag"
    ADD CONSTRAINT "ArticleTag_pkey" PRIMARY KEY ("tagId", "articleId");



ALTER TABLE ONLY public."Article"
    ADD CONSTRAINT "Article_pkey" PRIMARY KEY ("articleId");



ALTER TABLE ONLY public."Comment"
    ADD CONSTRAINT "Comment_pkey" PRIMARY KEY ("commentId");




ALTER TABLE ONLY public."Engagement"
    ADD CONSTRAINT "Engagement_pkey" PRIMARY KEY ("articleId");




ALTER TABLE ONLY public."Tag"
    ADD CONSTRAINT "Tag_pkey" PRIMARY KEY ("tagId");




ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY ("userId");




ALTER TABLE ONLY public."Subscription"
    ADD CONSTRAINT "subscriptionId_Pkey" PRIMARY KEY ("subscriptionId");

