INSERT INTO braindump."User"(
	"userId", "userName", "emailAddress", password, "createdTimestamp", "providerFlag", "iconFilename", biography)
	VALUES (1, 'Jim', 'jim@email.com', '1234', '2020-06-22 19:10:25-07', 'Y', 'rose.jpg', 'im awesome');

INSERT INTO braindump."User"(
	"userId", "userName", "emailAddress", password, "createdTimestamp", "providerFlag", "iconFilename", biography)
	VALUES (2, 'Abby', 'abby@email.com', '1234', '2020-06-22 19:10:25-07', 'N', 'rose.jpg', 'im awesome');

INSERT INTO braindump."User"(
	"userId", "userName", "emailAddress", password, "createdTimestamp", "providerFlag", "iconFilename", biography)
	VALUES (3, 'Homer', 'Homer@email.com', '1234', '2020-06-22 19:10:25-07', 'N', 'rose.jpg', 'im awesome');

INSERT INTO braindump."User"(
	"userId", "userName", "emailAddress", password, "createdTimestamp", "providerFlag", "iconFilename", biography)
	VALUES (4, 'Marge', 'Marge@email.com', '1234', '2020-06-22 19:10:25-07', 'Y', 'rose.jpg', 'im awesome');